{"timestamp":"2025-09-02T18:05:26.430452","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-02T18:05:26.431115","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/get_station_bicycle_info_data.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-02T18:05:26.503022","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"ConnectionError","exc_value":"HTTPSConnectionPool(host='velib-metropole-opendata.smovengo.cloud', port=443): Max retries exceeded with url: /opendata/Velib_Metropole/station_status.json (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7febe6a354c0>: Failed to resolve 'velib-metropole-opendata.smovengo.cloud' ([Errno -3] Temporary failure in name resolution)\"))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/get_station_bicycle_info_data.py","lineno":15,"name":"fetch_station_status"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/api.py","lineno":73,"name":"get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/api.py","lineno":59,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py","lineno":589,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py","lineno":703,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py","lineno":677,"name":"send"}],"is_group":false,"exceptions":[]},{"exc_type":"MaxRetryError","exc_value":"HTTPSConnectionPool(host='velib-metropole-opendata.smovengo.cloud', port=443): Max retries exceeded with url: /opendata/Velib_Metropole/station_status.json (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7febe6a354c0>: Failed to resolve 'velib-metropole-opendata.smovengo.cloud' ([Errno -3] Temporary failure in name resolution)\"))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py","lineno":644,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":519,"name":"increment"}],"is_group":false,"exceptions":[]},{"exc_type":"NameResolutionError","exc_value":"<urllib3.connection.HTTPSConnection object at 0x7febe6a354c0>: Failed to resolve 'velib-metropole-opendata.smovengo.cloud' ([Errno -3] Temporary failure in name resolution)","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":488,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":464,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":1093,"name":"_validate_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":753,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":205,"name":"_new_conn"}],"is_group":false,"exceptions":[]},{"exc_type":"gaierror","exc_value":"[Errno -3] Temporary failure in name resolution","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":198,"name":"_new_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":60,"name":"create_connection"},{"filename":"/usr/local/lib/python3.12/socket.py","lineno":978,"name":"getaddrinfo"}],"is_group":false,"exceptions":[]}]}
